# Generated by Django 6.0.4 on 2026-05-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_add_quarterly_financial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='fv_daily',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='fv_weekly',
            field=models.FloatField(default=0),
        ),
    ]
