# Generated by Django 6.0.4 on 2026-05-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_stockanalysis_fv_daily_stockanalysis_fv_weekly'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='intrinsic_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='valuation_status',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
