# Generated by Django 6.0.1 on 2026-05-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_add_fair_value_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='is_new_listing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='profit_growth_note',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
