# Generated by Django 6.0.4 on 2026-05-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_add_profit_growth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='rr_quality',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='rr_quality_detail',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='rr_warning',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
