# Generated by Django 6.0.4 on 2026-05-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_add_rr_quality_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='trailing_sl',
            field=models.FloatField(default=0),
        ),
    ]
