# Generated by Django 6.0.4 on 2026-05-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_add_trailing_sl_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('sector_code', models.CharField(blank=True, default='', max_length=20)),
                ('median_pe', models.FloatField(default=0)),
                ('median_pb', models.FloatField(default=0)),
                ('stock_count', models.IntegerField(default=0)),
                ('market_cap_avg', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Industry Valuations',
                'db_table': 'industry_valuation',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='sector_median_pe',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='valuation_cap_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='valuation_source',
            field=models.CharField(default='static', max_length=10),
        ),
    ]
