# Generated by Django 6.0.1 on 2026-05-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_add_industry_valuation_and_dynamic_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='recommendation_label',
            field=models.CharField(default='', max_length=50),
        ),
    ]
