# Generated by Django 6.0.1 on 2026-05-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_add_recommendation_label_field'),
        ('dashboard', '0021_add_earning_guidance_fields'),
    ]

    operations = [
    ]
