# Generated by Django 6.0.1 on 2026-05-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_merge_20260518_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysis',
            name='is_inverted_risk',
            field=models.BooleanField(default=False),
        ),
    ]
