# Generated by Django 6.0.1 on 2026-05-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_stockanalysis_is_inverted_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockanalysis',
            name='is_inverted_risk',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
